name: Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
        
      - name: Build documentation site
        run: |
          mkdir -p site
          
          # Create MkDocs configuration
          cat > mkdocs.yml << 'EOF'
          site_name: VMware PPTX Iconography
          site_description: Professional VMware iconography collection for PowerPoint presentations
          site_url: https://uldyssian-sh.github.io/vmware-pptx-iconography
          repo_url: https://github.com/uldyssian-sh/vmware-pptx-iconography
          repo_name: uldyssian-sh/vmware-pptx-iconography
          
          theme:
            name: material
            palette:
              - scheme: default
                primary: blue
                accent: blue
            features:
              - navigation.tabs
              - navigation.sections
              - navigation.expand
              - navigation.top
              - search.highlight
              - content.code.copy
          
          nav:
            - Home: index.md
            - Installation: installation.md
            - Usage Guide: usage-guide.md
            - Examples: examples.md
            - Contributing: contributing.md
          
          markdown_extensions:
            - admonition
            - codehilite
            - toc:
                permalink: true
          EOF
          
          # Copy documentation files
          cp README.md docs/index.md
          cp CONTRIBUTING.md docs/contributing.md
          
          # Create examples page
          cat > docs/examples.md << 'EOF'
          # Examples
          
          This page showcases various examples of VMware iconography usage in PowerPoint presentations.
          
          ## Architecture Diagrams
          
          Examples of how to create professional VMware architecture diagrams using the provided icons and templates.
          
          ## Template Gallery
          
          Browse through available PowerPoint templates designed for different presentation types.
          
          ## Best Practices
          
          Learn from real-world examples of effective VMware presentation design.
          EOF
          
          # Build site
          mkdocs build
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

