name: Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
        
      - name: Build documentation site
        run: |
          mkdir -p site
          
          # Create MkDocs configuration
          cat > mkdocs.yml << 'EOF'
          site_name: VMware PPTX Iconography
          site_description: Professional VMware iconography collection for PowerPoint presentations
          site_url: https://uldyssian-sh.github.io/vmware-pptx-iconography
          repo_url: https://github.com/uldyssian-sh/vmware-pptx-iconography
          repo_name: uldyssian-sh/vmware-pptx-iconography
          
          theme:
            name: material
            palette:
              - scheme: default
                primary: blue
                accent: blue
            features:
              - navigation.tabs
              - navigation.sections
              - navigation.expand
              - navigation.top
              - search.highlight
              - content.code.copy
          
          nav:
            - Home: index.md
            - Installation: installation.md
            - Usage Guide: usage-guide.md
            - Examples: examples.md
            - Contributing: contributing.md
          
          markdown_extensions:
            - admonition
            - codehilite
            - toc:
                permalink: true
          EOF
          
          # Copy documentation files
          cp README.md docs/index.md
          cp CONTRIBUTING.md docs/contributing.md
          
          # Create examples page
          cat > docs/examples.md << 'EOF'
          # Examples
          
          This page showcases various examples of VMware iconography usage in PowerPoint presentations.
          
          ## Architecture Diagrams
          
          Examples of how to create professional VMware architecture diagrams using the provided icons and templates.
          
          ## Template Gallery
          
          Browse through available PowerPoint templates designed for different presentation types.
          
          ## Best Practices
          
          Learn from real-world examples of effective VMware presentation design.
          EOF
          
          # Build site
          mkdocs build
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-site]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Package release assets
        run: |
          mkdir -p release
          
          # Package icons if they exist
          if [ -d icons ] && [ "$(find icons -type f | head -1)" ]; then
            echo "Packaging icons..."
            tar -czf release/vmware-icons-$(date +%Y%m%d).tar.gz icons/
          fi
          
          # Package templates if they exist
          if [ -d templates ] && [ "$(find templates -type f | head -1)" ]; then
            echo "Packaging templates..."
            tar -czf release/vmware-templates-$(date +%Y%m%d).tar.gz templates/
          fi
          
          # Package documentation
          echo "Packaging documentation..."
          tar -czf release/vmware-docs-$(date +%Y%m%d).tar.gz docs/ README.md
          
          # Create release notes
          cat > release/RELEASE_NOTES.md << 'EOF'
          # VMware PPTX Iconography Release
          
          ## What's Included
          
          - **Icons**: Professional VMware product icons in multiple formats
          - **Templates**: PowerPoint templates for various presentation types
          - **Documentation**: Comprehensive guides and examples
          
          ## Installation
          
          1. Download the appropriate package for your needs
          2. Extract to your desired location
          3. Follow the installation guide in the documentation
          
          ## Support
          
          For issues and questions, please visit our [GitHub repository](https://github.com/uldyssian-sh/vmware-pptx-iconography).
          EOF
          
      - name: Generate version tag
        id: version
        run: |
          VERSION="v$(date +%Y.%m.%d)-$(git rev-parse --short HEAD)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: VMware PPTX Iconography ${{ steps.version.outputs.version }}
          body_path: release/RELEASE_NOTES.md
          files: |
            release/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}